name: CI Node JS
on:
  push:
    branches:
      - main
      - release/**
      - hotfix
      - prod
    tags:
      - v*
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: "Running on  ${{ github.ref_type }} branch"
        run: |
          echo "I am Running from ${GITHUB_REF_NAME}""