name: CI Node JS
on:
  push:
    branches:
      - main
      - release/**
    tags:
      - v*
  create:
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Helo Helo"