name: CI Node JS
on:
  push:
    branches:
      - main
      - release/**
      - hotfix
      - prod
    tags:
      - v*
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: "Build on  ${{ github.ref_name }} branch"
        run: |
          echo "Build  from ${GITHUB_REF_NAME}"

  deploy:
    needs: build
    name: "Deploy/ ${{ github.ref_name }}"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' &&  (github.ref_name == 'main' || contains(github.ref_name, 'release') || github.ref_name == 'hotfix' || github.ref_type == 'tag')
    steps:
      - name: "Deploy on  ${{ github.ref_name }} branch"
        run: |
          echo "Deploy from ${GITHUB_REF_NAME}"
